### ISSUE TITLE
consecutive calls to show/hide is broken

### ISSUE THREAD

**Issue by kolodny** [milworm/react-progress-2#1]
I've forked and fixed it here, I need this right away so I didn't have time to make a PR, this is just an FYI

https://github.com/kolodny/react-progress-2/commit/fcfdb39fbfbf98bcd00b2e7ce8e1abd5a725e796#diff-1c90ff38a08209f9ebd4d05d1e43358eL1

**Comment by milworm** [comment]
Thanks for reporting a bug, just fixed them in https://github.com/milworm/react-progress-2/commit/09aea098c7bdf29ca3b41c53b5c6315b41571e17

**Comment by kolodny** [comment]
:+1:
