### ISSUE TITLE
unable to hide progress if show more than one time

### ISSUE THREAD

**Issue by jf3096** [milworm/react-progress-2#11]
Due to connect with react redux, progress.show has been invoked twice. Once this happened, I cannot hide it unless i call progress.hide twice as well

**Comment by jf3096** [comment]
Okay. According to your source code, u have used an counter to record number of times the show hide status have been called. I also found that you have expose a method hideAll which is helpful to fulfill my needs. May I know what your purpose of using such counter for?

**Comment by milworm** [comment]
Well, imagine you have page X. When user clicks on a button inside this page, app should make some request 1, show page Y (that also makes some requests 2,3). 
If you want to use hideAll in a callback for request 1, you'll find out that progress-bar will be hidden for requests 2, 3.
