### ISSUE TITLE
Uncaught TypeError: Cannot read property 'show' of undefined

### ISSUE THREAD

**Issue by gopinath-sixt** [milworm/react-progress-2#13]
Hi I am using Progress Component in multiple component on load. when i load one component is working fine. and the next component load is load, progress coponent work fine for this component, then load data for first component, it showing error "Uncaught TypeError: Cannot read property 'show' of undefined". 

please give solution

**Comment by milworm** [comment]
Hi, the component was designed as a singleton, so you should put it somewhere in your `<Layout />`.
Let me know if you still have any questions.

**Comment by gopinath-sixt** [comment]
Yeah It's worked when i added single "Progress component"  @ layout. but i planned "Progress component" to add in every component by using loader-60devs as position absolute. 

Cheers!!!
