### ISSUE TITLE
Issue with react-router

### ISSUE THREAD

**Issue by ventskus-roman** [milworm/react-progress-2#16]
Hi!

When I refresh the browser not on index page (for example /users) - I got an error 

`Uncaught (in promise) TypeError: Cannot read property 'querySelector' of undefined
    at Constructor.show (main.js:49)`
If I start from main page ('/') - all is ok

I use react-router, probably it is the reason of this issue. 
Is there some way to fix it?
I've tried to use `<Progress.Component/>` in parent component.
Also I've tried to place it over Router

```
<div>
  <Progress.Component/>
   <Router>
      ....
   </Router>
</div>
```

**Comment by milworm** [comment]
Hi @ventskus-roman 

They've updated react-router, so let's me check how to make it work with react-progress.
