### ISSUE TITLE
Getting `show of undefined` error when using in componentWillMount()

### ISSUE THREAD

**Issue by austinmao** [milworm/react-progress-2#2]
I want to use this as an indicator async loading indicator to indicate async route transitions. I have tried this below but it doesn't work because the component is not yet defined:

```
      componentWillMount() {
        if (!shouldNotShowProgressBar) {
          console.log('loading', api);
          Progress.show();
        }
      }

      componentDidMount() {
        if (!shouldNotShowProgressBar) {
          console.log('loaded', api);
          Progress.hide();
        }
      }
```

Do you have a working example of this?

**Comment by milworm** [comment]
Please check "Usage" section. Before calling #hide or #show methods, you need to put this line in your layout: <Progress.Component/>

**Comment by austinmao** [comment]
Yes, I did do that. But I think that the component is not mounted yet so Progress.show() was getting an undefined component.

**Comment by milworm** [comment]
But I think that the component is not mounted yet so Progress.show() was getting an undefined component. - yup!

**Comment by austinmao** [comment]
Ok, sorry let me edit my issue to be more clear. I am looking to have a loading indicator on route transitions like what http://ricostacruz.com/nprogress/ and https://github.com/reactjs/react-router/blob/master/examples/animations/app.js#L16-L25 does.

**Comment by milworm** [comment]
Well, you can use react-progress-2 to implement the same UX (and even a bit better ;)

Just place <Progress.Component> in App#render method, like this:
`render() {
  return <div><Progress.Component/> ...
}`

then implement Page1,2, etc... using this way:
https://gist.github.com/milworm/32b4b2e17a1f636281b6

Good luck!

**Comment by austinmao** [comment]
Unfortunately, this doesn't start until the component is already mounted, which is after the async data loading... so it isn't fired before the route transition.

**Comment by milworm** [comment]
Well, but who loads the data? is it App-class, or you make a request before App is mounted?

**Comment by austinmao** [comment]
I'm doing something like this: https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/containers/Widgets/Widgets.js

using the same library they're doing: https://github.com/Rezonans/redux-async-connect

**Comment by milworm** [comment]
I see, ok I have another idea :)
Update your index.html file to look like this:
https://gist.github.com/milworm/327588886f705fc66d60

then use React#render to render progress-bar separately from routes:
https://gist.github.com/milworm/620719f0312419dd2f3f

**Comment by austinmao** [comment]
I am trying this: https://gist.github.com/austinmao/1d9f5be9d1a6d30ca304
The progress bar shows up but it is never being hidden. It is overlaid on top of all other components and the other components are no longer clickable.

Thanks for your help!

**Comment by milworm** [comment]
It is overlaid on top of all other components and the other components are no longer clickable.
if you want, you can remove an invisible overlay by overriding css.

I probably need to know more to help you because it's more about the way you use it and not with a component itself.

Good luck!

**Comment by austinmao** [comment]
Thanks for your help. I figured out my issue. I was stacking `Progress.show()` because my props were not updating. I am doing this now:

```
  state = {
    isProgressShown: false
  };

  componentWillReceiveProps(next) {
    // hide progress bar if active and async data loaded
    const {isProgressShown} = this.state;
    if (!next.isAsyncDataLoaded && !isProgressShown) {
      Progress.show();
      this.setState({ isProgressShown: true });
    }

    if (next.isAsyncDataLoaded && isProgressShown) {
      Progress.hide();
      this.setState({ isProgressShown: false });
    }
  }
```

**Comment by milworm** [comment]
Good stuff! Tomorrow I will add #isVisible(), so you will be able to do Progress.isVisible()

**Comment by austinmao** [comment]
:+1: that would be great

**Comment by austinmao** [comment]
Might I also recommend adding `Progress.hideAll()` in order to clear everything that is shown? This would be particularly useful in `componentWillUnmount`
