### ISSUE TITLE
Uncaught ReferenceError: Progress is not defined

### ISSUE THREAD

**Issue by tarim** [milworm/react-progress-2#9]
Hi @milworm ,

I am trying to use your react-progress-2 to in my project. But, I got Progress is not defined error message. I don't know what I did missing.  need your help...

Thank you,

Here is my code: 

my header area: 1. header.js
import React,{Component} from 'react';
import { Link, IndexLink } from 'react-router';
import Progress from "react-progress-2";
export default class Header extends Component {
    constructor(){
        super();
    }
    render(){
        return( 
            <header id="header">
            <div id="logo-group">
                           </div>
            <Progress.Component/>
        </header> );
    }

}

my signin page:
import React, { Component, PropTypes } from 'react';
import { reduxForm } from 'redux-form';
import \* as api from '../api/authRepository';
export const fields = [ 'userName', 'password' ]

class Signin extends Component {
  handleFormSubmit({ userName, password }) {
       Progress.show();  // got error on this area
    this.props.signinUser({ userName, password });
  }

**Comment by OrKoN** [comment]
@tarim are you importing `import Progress from "react-progress-2";` in your sign-in page file?

**Comment by tarim** [comment]
Hi @OrKoN,

Thank you very much for your help, it is showing now, but, after show progress bar, none of clickable buttons can clickable any more. 

Any idea please?

thanks,

**Comment by milworm** [comment]
Hi @tarim,
This is a feature. There is an overlay on top of a page to prevent a user making any potentially dangerous operations while something is loading. If you want to disable this behaviour add the following lines to your css file:

``` css
/* disable mask */
.loader-60devs::before {
  display: none;
}
```

**Comment by tarim** [comment]
Thank you @milworm , It works.
